set_property SRC_FILE_INFO {cfile:G:/Xilinx_2022/Vivado/2022.1/proyek/switches_to_led/switches_to_led.srcs/constrs_1/new/switches_leds_constrain.xdc rfile:../../../switches_to_led.srcs/constrs_1/new/switches_leds_constrain.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G19 [get_ports switch]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports led]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property DIRECTION OUT [get_ports led]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property DIRECTION IN [get_ports switch]
